version: "2.1"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${timezone}
      - URL=${domain}
      - SUBDOMAINS=${subdomains}
      - EMAIL=${email}
      - VALIDATION=${challenge_type}
      - ONLY_SUBDOMAINS=${only_subdomains}
      - STAGING=${staging}
    volumes:
      - ${app_context}/config:/config
      - ${app_context}/data:/data
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped